### ISSUE TITLE
`py.typed` file is not included in releases

### ISSUE THREAD

**Issue by shenanigansd** [letsbuilda/letsbuilda-pypi#67]
We need to add it as package data to get it into the releases
```toml
[tool.setuptools.package-data]
"letsbuilda.pypi" = ["py.typed"]
```
